//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENEStock.Service.Models
{
    using System;
    using System.Collections.Generic;

    public partial class stockprice
    {
        public string id { get; set; }
        public string stockcode { get; set; }
        public string codename { get; set; }
        public Nullable<double> lastprice { get; set; }
        public Nullable<double> openprice { get; set; }
        public Nullable<double> newprice { get; set; }
        public Nullable<double> highestprice { get; set; }
        public Nullable<double> lowestprice { get; set; }
        public Nullable<double> turnover { get; set; }
        public Nullable<double> tradingvolume { get; set; }
        public Nullable<double> changeamount { get; set; }
        public Nullable<double> changerate { get; set; }
        public Nullable<double> amplitude { get; set; }
        public Nullable<System.DateTime> tradetime { get; set; }
    }
}
