//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENEStock.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockdetail
    {
        public string id { get; set; }
        public string stockid { get; set; }
        public string stockname { get; set; }
        public string stockcode { get; set; }
        public Nullable<double> zxj { get; set; }
        public Nullable<double> zde { get; set; }
        public Nullable<double> zdf { get; set; }
        public Nullable<double> zs { get; set; }
        public Nullable<double> jk { get; set; }
        public Nullable<double> zgj { get; set; }
        public Nullable<double> zdj { get; set; }
        public Nullable<int> cjl { get; set; }
        public Nullable<double> cje { get; set; }
        public Nullable<double> jlr { get; set; }
        public Nullable<double> hsl { get; set; }
        public Nullable<System.DateTime> rtime { get; set; }
    }
}
